from . import sadgfx as sg

# Light
BACKGROUND = sg.WHITE
BACKGROUND_TEXT = sg.BLACK
PRIMARY = sg.ORANGE
PRIMARY_TEXT = sg.WHITE
SECONDARY = sg.PURPLE2
SECONDARY_TEXT = sg.WHITE

# Dark
# BACKGROUND = sg.BLACK
# BACKGROUND_TEXT = sg.WHITE
# PRIMARY = sg.ORANGE
# PRIMARY_TEXT = sg.WHITE
# SECONDARY = sg.PURPLE2
# SECONDARY_TEXT = sg.WHITE
