[app]
name = "Wurzelitzer"
menu = "Music"
wifi_preference = true

[entry]
class = "JukeBox"

[metadata]
author = "Flow3r Badge Authors"
license = "LGPL-3.0-only"
url = "https://git.flow3r.garden/flow3r/flow3r-firmware"
