WHITE = (1.0, 1.0, 1.0)
BLACK = (0.0, 0.0, 0.0)
ORANGE = (1.0, 0.4, 0.0)
PURPLE = (0.65, 0.0, 0.84)

# Light
# BACKGROUND = WHITE
# BACKGROUND_TEXT = BLACK
# PRIMARY = ORANGE
# PRIMARY_TEXT = WHITE
# SECONDARY = PURPLE
# SECONDARY_TEXT = WHITE

# Dark
BACKGROUND = BLACK
BACKGROUND_TEXT = WHITE
PRIMARY = ORANGE
PRIMARY_TEXT = WHITE
SECONDARY = PURPLE
SECONDARY_TEXT = WHITE
