WHITE = (1.0, 1.0, 1.0)
BLACK = (0.0, 0.0, 0.0)
ORANGE = (1.0, 0.4, 0.0)
PURPLE = (0.65, 0.0, 0.84)
PUSH_PINK = (0.98, 0.28, 0.77)
GO_GREEN = (0.25, 1.0, 0.13)

# Light
# BACKGROUND = WHITE
# BACKGROUND_TEXT = BLACK
# PRIMARY = PUSH_PINK
# PRIMARY_TEXT = WHITE
# SECONDARY = GO_GREEN
# SECONDARY_TEXT = WHITE

# Dark
BACKGROUND = BLACK
BACKGROUND_TEXT = WHITE
PRIMARY = PUSH_PINK
PRIMARY_TEXT = WHITE
SECONDARY = GO_GREEN
SECONDARY_TEXT = WHITE
