[app]
name = "I2C/Qwiic Scanner"
category = "Apps"

[entry]
class = "I2CScanner"

[metadata]
author = "Flow3r Badge Authors"
license = "LGPL-3.0-only"
url = "https://git.flow3r.garden/flow3r/flow3r-firmware"
