[app]
name = "Get Apps"
category = "Hidden"
wifi_preference = true

[entry]
class = "Gr33nhouseApp"

[metadata]
author = "Flow3r Badge Authors"
license = "LGPL-3.0-only"
url = "https://git.flow3r.garden/flow3r/flow3r-firmware"
