import bl00mbox

from typing import List

class _Patch: ...

class tinysynth(_Patch):
    def decay(self, v: float) -> None: ...
    def waveform(self, v: int) -> None: ...
    def attack(self, v: float) -> None: ...
    def volume(self, v: float) -> None: ...
    def sustain(self, v: float) -> None: ...
    def release(self, v: float) -> None: ...
    def tone(self, v: float) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...

class tinysynth_fm(tinysynth):
    def fm_waveform(self, v: int) -> None: ...
    def fm(self, v: float) -> None: ...

class step_sequencer(_Patch):
    seqs: List[bl00mbox.Bud]
    bpm: int

    def trigger_state(self, track: int, i: int) -> bool: ...
    def trigger_toggle(self, track: int, i: int) -> None: ...

class sampler(_Patch):
    sampler: bl00mbox.Bud
