[app]
name = "melodic demo"
category = "Hidden"

[entry]
class = "MelodicApp"

[metadata]
author = "Flow3r Badge Authors"
license = "LGPL-3.0-only"
url = "https://git.flow3r.garden/flow3r/flow3r-firmware"
