[app]
name = "Audio Passthrough"
menu = "Media"

[entry]
class = "AudioPassthrough"

[metadata]
author = "ave"
license = "LGPL-3.0-only"
url = "https://git.flow3r.garden/flow3r/flow3r-firmware"
description = "Allows toggling audio passthrough through line-in/mic to speaker or lineout."
version = 7
