CTX_MOD_DIR := $(USERMOD_DIR)
SRC_USERMOD += $(addprefix $(CTX_MOD_DIR)/, \
	uctx.c \
)
CFLAGS_USERMOD += -I$(CTX_MOD_DIR) -DMODULE_CTX_ENABLED=1 -I$(CTX_MOD_DIR)/../fonts
# CFLAGS_USERMOD += -DEXPOSE_EXTRA_METHODS=1
