import time

from st4m.ui.ctx import Ctx

def freertos_sleep(ms: int) -> None: ...
def get_ctx() -> Ctx: ...
def display_pipe_full() -> bool: ...
def display_pipe_flush() -> None: ...
def display_update(c: Ctx) -> None: ...
def display_set_backlight(percent: int) -> None: ...
def usb_connected() -> bool: ...
def usb_console_active() -> bool: ...
def version() -> str: ...
def i2c_scan() -> list[int]: ...
def captouch_calibration_active() -> int: ...
def get_captouch(ix: int) -> bool: ...
def captouch_get_petal_pad_raw(petal: int, pad: int) -> int: ...
def captouch_get_petal_pad(petal: int, pad: int) -> int: ...
def captouch_get_petal_rad(petal: int) -> int: ...
def captouch_get_petal_phi(petal: int) -> int: ...
def captouch_set_petal_pad_threshold(petal: int, pad: int, thres: int) -> None: ...
def captouch_autocalib() -> None: ...
def captouch_set_calibration_afe_target(target: int) -> None: ...
def menu_button_get() -> int: ...
def application_button_get() -> int: ...
def left_button_get() -> int: ...
def right_button_get() -> int: ...
def menu_button_set_left(left: int) -> None: ...
def menu_button_get_left() -> int: ...
def scope_draw(ctx: Ctx) -> None: ...

BUTTON_PRESSED_LEFT: int
BUTTON_PRESSED_RIGHT: int
BUTTON_PRESSED_DOWN: int
BUTTON_NOT_PRESSED: int
