import time

from ctx import Context

def freertos_sleep(ms: int) -> None: ...
def get_ctx() -> Context: ...
def display_pipe_full() -> bool: ...
def display_pipe_flush() -> None: ...
def display_update(c: Context) -> None: ...
def display_set_backlight(percent: int) -> None: ...
def usb_connected() -> bool: ...
def usb_console_active() -> bool: ...
def version() -> str: ...
def i2c_scan() -> list[int]: ...
def menu_button_get() -> int: ...
def application_button_get() -> int: ...
def left_button_get() -> int: ...
def right_button_get() -> int: ...
def menu_button_set_left(left: int) -> None: ...
def menu_button_get_left() -> int: ...
def scope_draw(ctx: Context) -> None: ...

BUTTON_PRESSED_LEFT: int
BUTTON_PRESSED_RIGHT: int
BUTTON_PRESSED_DOWN: int
BUTTON_NOT_PRESSED: int
