import time

from st4m.ui.ctx import Ctx


def freertos_sleep(ms: int) -> None: ...

def get_ctx() -> Ctx: ...

def display_pipe_full() -> bool: ...

def display_update(c: Ctx) -> None: ...

def get_captouch(ix: int) -> bool: ...

def left_button_get() -> int: ...

def right_button_get() -> int: ...

def usb_connected() -> bool: ...

def usb_console_active() -> bool: ...
