from st3m.goose import Optional

STA_IF: int

class WLAN:
    def __init__(self, mode: int) -> None: ...
    def active(self, active: bool) -> bool: ...
    def connect(self, ssid: bytes, key: Optional[bytes] = None) -> None: ...
    def isconnected(self) -> bool: ...
    def status(self, s: str) -> float: ...
