from typing import Any

DIRTYPE = "dir"
REGTYPE = "file"

class TarInfo:
    name: str
    size: int
    type: str

    def __str__(self) -> str: ...

class TarFile:
    def __init__(self, name: Any = None, fileobj: Any = None): ...
    def next(self) -> TarInfo: ...
    def __iter__(self) -> TarFile: ...
    def __next__(self) -> TarInfo: ...
    def extractfile(self, tarinfo: TarInfo) -> Any: ...
